[package]
name = "contract-utils"
version = "0.1.0"
authors = ["Maciej Zielinski <maciek.s.zielinski@gmail.com>"]
edition = "2018"

[dependencies]
casper-contract = "4.0.0"
casper-types = "4.0.1"
hex = { version = "0.4.3", default-features = false }
