[package]
name = "contract-storage"
version = "0.2.0"
authors = ["akirapham <vancam.pham@hotmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
casper-types = "4.0.1"
proc-macro2 = "1.0.26"
quote = "1.0.9"
syn = "2.0.23"
convert_case = "0.6.0"
regex = "1.8.4"